# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.
# This file defines charm config options, and populates the Configure tab on Charmhub.
# If your charm does not require configuration options, delete this file entirely.
#
# See https://juju.is/docs/config for guidance.

options:
  location:
    description: |
      The URL to this set of backends is tied to, e.g., ubuntu.com/about. Regex is not 
    type: string
  backends:
    description: |
      A comma-separated list of IPs. If multiple IPs are provided, the access to the backends will 
      be load-balanced.
    type: string
  protocol:
    description: |
      The protocol to request the backends. Can be http or https.
    type: string
    default: https
