# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.
# This file defines charm config options, and populates the Configure tab on Charmhub.
# If your charm does not require configuration options, delete this file entirely.
#
# See https://juju.is/docs/config for guidance.

options:
  location:
    description: |
      The URL to this set of backends is tied to, e.g., ubuntu.com/about.
    type: string
  backends:
    description: |
      A comma-separated list of IPs and ports in PROTOCOL:IP format for the backends serving the
      content to cache, e.g., https:10.10.10.10, http:10.10.1.1. The protocols available are http
      and https. Port 80 will be used for http, and port 443 for https. If multiple IPs are 
      provided, the access to the backends will be load-balanced.
    type: string
